# Generated by Django 2.2.1 on 2019-07-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190718_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='device_id',
            field=models.CharField(default='', max_length=17),
            preserve_default=False,
        ),
    ]
