# Generated by Django 2.2.3 on 2019-08-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_measurement_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='diff_a',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='diff_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='diff_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='diff_z',
            field=models.FloatField(null=True),
        ),
    ]
