# Generated by Django 2.2.5 on 2019-09-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190830_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.CharField(default='', max_length=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='diff_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='diff_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='diff_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='diff_z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
