# Generated by Django 2.2.5 on 2019-12-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='t_max',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='device',
            name='t_min',
            field=models.FloatField(default=-10.0),
        ),
        migrations.AddField(
            model_name='device',
            name='x_max',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='device',
            name='x_min',
            field=models.FloatField(default=-10.0),
        ),
        migrations.AddField(
            model_name='device',
            name='y_max',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='device',
            name='y_min',
            field=models.FloatField(default=-10.0),
        ),
        migrations.AddField(
            model_name='device',
            name='z_max',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='device',
            name='z_min',
            field=models.FloatField(default=-10.0),
        ),
    ]
