# Generated by Django 3.0.2 on 2020-01-11 08:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191201_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
